FROM tensorflow/tensorflow:latest-gpu-jupyter

ARG USERNAME=jschaupp
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 \ 
    && pip3 install pandas numpy matplotlib pillow cityscapesscripts ipykernel