FROM tensorflow/tensorflow:latest-gpu-jupyter

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121 \ 
    && pip3 install pandas numpy matplotlib pillow 